apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: demo-azure-keyvault-secret
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"      
    keyvaultName: "rothiekvcsivault"
    tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47"
    objects:  |
      array:
        - |
          objectName: TestSecret
          objectType: secret
  secretObjects:
    - secretName: demo-key-vault-secret
      type: Opaque 
      data:
      - key: TestSecret
        objectName: TestSecret
---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: demo-azure-keyvault-cert
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"      
    keyvaultName: "rothiekvcsivault"
    tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47"
    objects:  |
      array:
        - |
          objectName: TestCertificate
          objectType: secret
  secretObjects:
    - secretName: demo-key-vault-cert
      type: kubernetes.io/tls
      data:
      - key: tls.crt
        objectName: TestCertificate
      - key: tls.key
        objectName: TestCertificate
