apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cloud-secret-store
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName
    value: rothiesecretsdemovault
