apiVersion: apps/v1
kind: Deployment
metadata:
  name: secretsdemo
spec:
  selector:
    matchLabels:
      app: secretsdemo
  template:
    metadata:
      labels:
        app: secretsdemo
        aadpodidbinding: default-aad-pod-identity
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "app"
        dapr.io/app-port: "80"
    spec:
      containers:
      - name: app
        image: robinmanuelthiel/dapr-secrets-demo:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
