apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cloud-secret-store
  namespace: default
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName
    value: rothiesecretsdemovault
  - name: azureTenantId
    secretKeyRef:
      name: DevAppServicePrincipalTenantId
      key:  DevAppServicePrincipalTenantId
  - name: azureClientId
    secretKeyRef:
      name: DevAppId
      key:  DevAppId
  - name: azureClientSecret
    secretKeyRef:
      name: DevAppServicePrincipalPassword
      key:  DevAppServicePrincipalPassword
auth:
  secretStore: local-secret-store
